python train_mapping.py \
--use_v2_degradation \
--training_dataset mapping \
--use_vae_which_epoch 200 \
--continue_train \
--name mapping_quality \
--label_nc 0 \
--loadSize 256 \
--fineSize 256 \
--no_instance \
--resize_or_crop crop_only \
--batchSize 80 --no_html \
--gpu_ids 0 \
--nThreads 8 \
--l2_feat 60 \
--n_downsample_global 3 \
--mc 64 --k_size 4 \
--start_r 1 --mapping_n_block 6 \
--map_mc 512 --use_l1_feat \
--niter 150 --niter_decay 100 \
--load_pretrainA [ckpt_of_domainA_SR_old_photos] \
--load_pretrainB [ckpt_of_domainB_old_photos] \
--dataroot [your_data_folder] \
--outputs_dir [your_output_folder] \
--checkpoints_dir [your_ckpt_folder]
